ALTER TABLE sms ADD ref_id TEXT NOT NULL DEFAULT 'N/A';
ALTER TABLE sms ADD cost VARCHAR(255) NOT NULL DEFAULT 'N/A';
ALTER TABLE sms ADD description TEXT NOT NULL DEFAULT 'N/A';
ALTER TABLE sms ADD callback_status VARCHAR(255) NOT NULL DEFAULT 'N/A';